### ISSUE TITLE
on click change boarder color

### ISSUE THREAD

**Issue by D063520** [WikidataComplete/Wikidata-Complete-Gadget#31]
I suggest to change the boarder solor to #0645ad when we click it looks like this
<img width="947" alt="Screenshot 2021-08-23 at 13 35 54" src="https://user-images.githubusercontent.com/10883585/130440804-02135e8a-851f-4c4c-b0d0-2ffeec2fec80.png">

**Comment by D063520** [comment]
when done, remember to add here:

https://www.wikidata.org/w/index.php?title=Wikidata:Tools/Enhance_user_interface&action=edit

a screenshot

1) upload to wikimedia commons
2) add a 
|screenshot = Wikidata Gadget CreateNewItem Screenshot - 1.png
tag like this

**Comment by Dhairya3124** [comment]
Fix: https://github.com/Dhairya3124/Wikidata-Complete-Gadget/commit/67ca0eecf3edac5c5399b01c3e252783094f8759

**Comment by D063520** [comment]
it should be gray at the beginning, without having opened it ... and  blue after ....

not like this ....
<img width="1076" alt="Screenshot 2021-08-24 at 14 12 08" src="https://user-images.githubusercontent.com/10883585/130614255-b7e7fb4d-3620-4edc-ab5b-d17f03341c33.png">

**Comment by Dhairya3124** [comment]
Fix: https://github.com/Dhairya3124/Wikidata-Complete-Gadget/commit/b94e7aed31314b776c55437ac69f37efc9dda805

**Comment by D063520** [comment]
it is fine, except that when there is no statement to approve one has to click twice now .....

**Comment by D063520** [comment]
when there is no statement it should remain gray ....

**Comment by Dhairya3124** [comment]
Okay I'll fix this :+1:
