### ISSUE TITLE
Prevent duplication suggestions

### ISSUE THREAD

**Issue by anbo-de** [WikidataComplete/Wikidata-Complete-Gadget#33]
## DoD

* [x] Duplicate suggestions are prevented

## Example

At https://www.wikidata.org/wiki/Q10085467 just one suggestion should be shown.

![image](https://user-images.githubusercontent.com/6186824/131151463-0ef39853-df40-4345-8d81-3c40deef1a1e.png)

**Comment by anbo-de** [comment]
Solved some time ago.

**Comment by lalit97** [comment]
appeared again today for https://www.wikidata.org/wiki/Q11296747


![Screenshot from 2022-07-08 13-33-55](https://user-images.githubusercontent.com/31045288/177946535-dcf3443a-0eb3-444e-96ff-adfc0ba94fee.png)

**Comment by lalit97** [comment]
This is fixed permanently by adding django's `unique together` check on the database level in the backend ([backend/models.py#33](https://github.com/WikidataComplete/wikidatacomplete-backend/pull/56/files#diff-97796af1ae2adc055cf16d38132869b3edd05500584b3683003794b120d38084R33)). Also the existing duplicate records are removed from the database by a one time script.
