### ISSUE TITLE
fix UI for mobile devices

### ISSUE THREAD

**Issue by lalit97** [WikidataComplete/Wikidata-Complete-Gadget#46]
as per talk page message by user we need to fix UI for mobile devices

**Comment by anbo-de** [comment]
@lalit97 Please ask the bug reporter about his/her display resolution.

**Comment by lalit97** [comment]
Thanks for the reminder @anbo-de. I have already asked the user. He is using `Samsung galaxy s21, chrome 104 on android 12`.
![Screenshot from 2022-08-09 12-50-44](https://user-images.githubusercontent.com/31045288/183589113-2223128f-bd55-4099-955d-881f898709b9.png)

**Comment by lalit97** [comment]
close with #49
